"""add_professional_profile_fields

Revision ID: 28e95fb25eb9
Revises: c1b76808b6bd
Create Date: 2025-12-16 01:58:57.528041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28e95fb25eb9'
down_revision: Union[str, None] = 'c1b76808b6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_user_events_event_type', table_name='user_events')
    # op.drop_index('ix_user_events_id', table_name='user_events')
    # op.drop_index('ix_user_events_user_id', table_name='user_events')
    # op.drop_table('user_events')
    op.add_column('student_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('student_profiles', sa.Column('portfolio_url', sa.String(length=255), nullable=True))
    op.add_column('student_profiles', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('target_role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'target_role')
    op.drop_column('student_profiles', 'experience_years')
    op.drop_column('student_profiles', 'portfolio_url')
    op.drop_column('student_profiles', 'linkedin_url')
    op.drop_column('student_profiles', 'bio')
    op.create_table('user_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_events_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_events_pkey')
    )
    op.create_index('ix_user_events_user_id', 'user_events', ['user_id'], unique=False)
    op.create_index('ix_user_events_id', 'user_events', ['id'], unique=False)
    op.create_index('ix_user_events_event_type', 'user_events', ['event_type'], unique=False)
    # ### end Alembic commands ###
