"""add_persist_columns_v3

Revision ID: 51d0118c4416
Revises: 7538d4309f6a
Create Date: 2025-12-22 08:27:49.549773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d0118c4416'
down_revision: Union[str, None] = '7538d4309f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('skill_analysis', sa.Text(), nullable=True))
    op.drop_column('student_profiles', 'roadmap_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('roadmap_progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('student_profiles', 'skill_analysis')
    # ### end Alembic commands ###
