"""create_student_profile_table

Revision ID: c1b76808b6bd
Revises: 
Create Date: 2025-12-13 14:25:57.515566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b76808b6bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('current_semester', sa.String(length=50), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('interests', sa.String(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('has_resume', sa.Boolean(), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('resume_file_path', sa.String(length=500), nullable=True),
    sa.Column('parsed_resume_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
